on:
  # Triggers the workflow on push or pull request events but only for the main branch.
  push: 
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v3

      # Runs a single command using the runner shell
      - name: Send greeting
        run: echo "Hello from GitHub Actions!"
