# Controls when the workflow will run
on:
  # Triggers the workflow on  push or pull request events but only for the main branch.
  push: 
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow is made up of one or more jobs that can run sequentially or parallel.
  jobs:
    # This workflow contains a single job called "build"
    build:
    # The type of runner that job will run on
    runs-on: ubuntu-latest

    steps:
    # Runs a single command using the runner shell
    - name: Send greeting
    run: echo "Hello ${{ github.event.inputs.name }}
    
